# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

i_am_a_sponsor: true

# Appearance
appearance:
  mode: light
  color: indigo

# SEO
marketing:
  seo:
    site_type: OnlineBusiness
    local_business_type: ''
    org_name: 'Natixar'
    description: 'ESG & traceability solutions in real time'
    twitter: ''
  analytics:
    google_tag_manager: ''  # Google Tag Manager ID
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "logo_natixxar_gray.png"
    button:
      enable: false
      text: "Get Started"
      url: "https://hugoblox.com/templates/"
    show_search: true
    show_theme_chooser: true
    show_translations: true
    hide_language_name: false

# Site footer
footer:
  copyright:
    notice: 'Â© {year} Natixar'
    built_with: false
    license: 
      enable: true

# Localization
locale:
  date_format: '2 January 2006'
  time_format: '23:04'
  address_format: 'fr-fr'  # Use 'fr-fr' for French format
